version: '3.8'

volumes:
  postgres-data: null
services:
  app:
    hostname: app.dachshund.local
    networks:
      - dachshund
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Go version 1, 1.18, 1.17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: '1.18'
        # Options
        NODE_VERSION: 'lts/*'
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    # Security Opt and cap_add allow for C++ based debuggers to work.
    # See `runArgs`: https://github.com/Microsoft/vscode-docs/blob/main/docs/remote/devcontainerjson-reference.md
    #     security_opt:
    #       - seccomp:unconfined
    #     cap_add:
    #       - SYS_PTRACE

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    networks:
      - dachshund
    image: postgres:latest
    hostname: db.dachshund.local
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOSTNAME=localhost
    volumes:
      - postgres-data:/var/lib/postgresql/data
    

  mailhog:
    networks:
      - dachshund
    image: mailhog/mailhog:latest
    hostname: mailhog.dachshund.local
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

networks:
  dachshund:
    driver: bridge
